// ============================================// 教案生成引擎 - 配置信息// ============================================
import type { AgeGroup, AgeGroupConfig, ThemeConfig, Intensity } from './types';

// 年龄段配置
export const AGE_GROUP_CONFIG: Record<AgeGroup, AgeGroupConfig> = {
  U6: {
    name: 'U6 (4-6岁 幼儿班)',
    minAge: 4,
    maxAge: 6,
    sections: ['etiquette', 'warmup', 'ball_familiarity', 'game', 'cooldown', 'etiquette'],
    warmupDuration: 8,
    ballFamDuration: 20,
    technicalDuration: 10,
    physicalDuration: 10,
    tacticalDuration: 0,
    gameDuration: 20,
    cooldownDuration: 8,
    etiquetteDuration: 4,
    maxDifficulty: 2,
    recommendedSkills: ['dribbling', 'shooting'],
    avoidActivities: ['对抗比赛', '复杂战术', '背后运球'],
    hasEtiquette: true,
  },
  U8: {
    name: 'U8 (7-8岁 小学低年级)',
    minAge: 7,
    maxAge: 8,
    sections: [
      'etiquette',
      'warmup',
      'ball_familiarity',
      'technical',
      'game',
      'cooldown',
      'etiquette',
    ],
    warmupDuration: 6,
    ballFamDuration: 12,
    technicalDuration: 25,
    physicalDuration: 10,
    tacticalDuration: 5,
    gameDuration: 20,
    cooldownDuration: 6,
    etiquetteDuration: 4,
    maxDifficulty: 2,
    recommendedSkills: ['dribbling', 'passing', 'shooting'],
    avoidActivities: ['复杂挡拆'],
    hasEtiquette: true,
  },
  U10: {
    name: 'U10 (9-10岁 小学中年级)',
    minAge: 9,
    maxAge: 10,
    sections: [
      'etiquette',
      'warmup',
      'technical',
      'physical',
      'tactical',
      'game',
      'cooldown',
      'etiquette',
    ],
    warmupDuration: 6,
    ballFamDuration: 5,
    technicalDuration: 25,
    physicalDuration: 15,
    tacticalDuration: 15,
    gameDuration: 18,
    cooldownDuration: 6,
    etiquetteDuration: 4,
    maxDifficulty: 3,
    recommendedSkills: ['dribbling', 'passing', 'shooting', 'defending'],
    avoidActivities: [],
    hasEtiquette: true,
  },
  U12: {
    name: 'U12 (11-12岁 小学高年级/初一)',
    minAge: 11,
    maxAge: 12,
    sections: [
      'etiquette',
      'warmup',
      'technical',
      'physical',
      'tactical',
      'game',
      'cooldown',
      'etiquette',
    ],
    warmupDuration: 6,
    ballFamDuration: 0,
    technicalDuration: 22,
    physicalDuration: 18,
    tacticalDuration: 18,
    gameDuration: 22,
    cooldownDuration: 6,
    etiquetteDuration: 4,
    maxDifficulty: 4,
    recommendedSkills: ['dribbling', 'passing', 'shooting', 'defending', 'tactical'],
    avoidActivities: [],
    hasEtiquette: true,
  },
  U14: {
    name: 'U14 (13-14岁 初二/初三)',
    minAge: 13,
    maxAge: 14,
    sections: [
      'etiquette',
      'warmup',
      'technical',
      'physical',
      'tactical',
      'game',
      'cooldown',
      'etiquette',
    ],
    warmupDuration: 5,
    ballFamDuration: 0,
    technicalDuration: 20,
    physicalDuration: 20,
    tacticalDuration: 22,
    gameDuration: 25,
    cooldownDuration: 5,
    etiquetteDuration: 3,
    maxDifficulty: 5,
    recommendedSkills: ['dribbling', 'passing', 'shooting', 'defending', 'tactical', 'physical'],
    avoidActivities: [],
    hasEtiquette: true,
  },
};

// 主题配置
export const THEME_CONFIG: Record<string, ThemeConfig> = {
  运球基础: {
    skills: ['dribbling'],
    categories: ['technical', 'ball_familiarity'],
    intensity: 'medium',
  },
  传球技术: {
    skills: ['passing'],
    categories: ['technical'],
    intensity: 'medium',
  },
  投篮训练: {
    skills: ['shooting'],
    categories: ['technical'],
    intensity: 'medium',
  },
  防守入门: {
    skills: ['defending'],
    categories: ['technical'],
    intensity: 'medium',
  },
  进攻战术: {
    skills: ['tactical'],
    categories: ['tactical'],
    intensity: 'high',
  },
  防守战术: {
    skills: ['defending', 'tactical'],
    categories: ['tactical'],
    intensity: 'high',
  },
  体能训练: {
    skills: ['physical'],
    categories: ['physical'],
    intensity: 'high',
  },
  综合训练: {
    skills: ['dribbling', 'passing', 'shooting'],
    categories: ['technical', 'game'],
    intensity: 'medium',
  },
  对抗比赛: { skills: [], categories: ['game'], intensity: 'high' },
  考核评估: {
    skills: ['dribbling', 'passing', 'shooting'],
    categories: ['technical'],
    intensity: 'medium',
  },
  球性熟悉: {
    skills: ['dribbling'],
    categories: ['ball_familiarity'],
    intensity: 'low',
  },
  中考体育: {
    skills: ['physical'],
    categories: ['physical'],
    intensity: 'medium',
  },
};
